### ISSUE TITLE
连续播放的时候下一首歌不从头开始

### ISSUE THREAD

**Issue by zidongtuili** [nondanee/NetEaseMusicWorldPlus#1]
好像连续播放的时候基本上每一首歌都要从中间的地方开始播放，有点像记忆了播放位置一样，不知道是不是和这个插件相关

**Comment by nondanee** [comment]
@zidongtuili 
我试了下应该是有关的，不过单从插件工作机制上讲应该是不影响的
可能是因为插件重定向了歌曲 url 触发了网易云自己的 bug（也可能是 feature）
我看国内现在已经不用直链了，还封装了一层，也有可能是加了 anti 的机制
所以暂时修不了，我想想办法看能不能避免了

你注意一下是不是从中间播放的位置是不是上首歌结束的时刻
比如上首长度 4:18 下首是 5:15，循环播放后直接从下一首 4:19 开始播放
还有一个 bug ，有时上一首播放时拖到 0:30 后直接点下一首，下一首也会从 0:30 开始播放那个

这两个问题我这边都不是 100% 复现，具体原因不清楚

**Comment by zidongtuili** [comment]
今天好像还没有重现这个问题。不过想起来还有个问题就是有的歌曲直接就加载不动。当然我配合猴油320k的脚本在用。大神现在linux没有root权限的情况下推荐的网易云音乐方案目前是这个吗？还是别的客户端(api)之类的

**Comment by nondanee** [comment]
@zidongtuili 
不好意思最近回国了所以暂时不需要 unblock 😂
有些歌曲可能本来就有问题，比如在 NetEaseMusicWorld 的 issue 里提到的这首 [BWV 306 - 巴赫](https://music.163.com/#/song?id=26025710)，应该是网易云自己的问题

不清楚你说的网易云音乐方案是指什么，是指解除海外墙吗？
最优方案肯定是代理回国内呀，解决一切烦恼 😂

- 网页版
就用这个插件吧
- Linux 上的网易云客户端
用这个 [nondanee/UnblockNeteaseMusic](https://github.com/nondanee/UnblockNeteaseMusic)
- 第三方客户端 
去改一下源码自编译（重定向你懂的）
[trazyn/ieaseMusic](https://github.com/trazyn/ieaseMusic) 
[Rocket1184/electron-netease-cloud-music](https://github.com/Rocket1184/electron-netease-cloud-music)
其它做得比较糙的我就不推荐了
- 用 VS Code 听歌了解一下
[nondanee/vsc-netease-music](https://github.com/nondanee/vsc-netease-music)（暂未上架）

**Comment by zidongtuili** [comment]
大佬太客气了。我试了一下确实是下一首歌从上一首结束的地方开始。
主要这个学校的机器没有root,源码改bin位置我还能搞定，缺库就麻烦了。docker好像是装不上,npm(node.js?)不知道能不能免root运行其中的。这个linux客户端好像是个修改协议的工具？好像要配合Linux客户端？我这个是基于red hat的，估计客户端是deb吧（rpm的估计没有root也装不了了）。第三方和vs code带unblock效果吗？想想算了不折疼了，还不如套个虚拟机了 (>_< 打不出你那种表情符)
一下这么详细我都不好意思了。
代理总觉得数据从中转走了一遍，空转了硬盘，浪费了电和带宽，而且还有隐私。这种音乐的媒体类尽量不走。不过想想互联网充满了中间缓存的节点，只不过有些不认为是代理……

**Comment by zidongtuili** [comment]
对了，windows客户端已经可以直接用了，不知道是客户端有特殊的密钥/身份识别？还是仅仅通道不一样，如果仅仅是通道不一样不知道是不是可以直接改网页的定向。还有BWV 306 巴赫我网页版是能放的

**Comment by nondanee** [comment]
不好意思感冒了有点难受，没有尽快回复你

网易云官方的 Linux 客户端是 deb 的；那些第三方的一般不带 unblock 海外墙 效果，需要改一下源码，重定向歌曲链接一下就行；vscode 那个扩展有 unblock 海外墙 功能，但是 vscode 本身是 rpm 可能你也没法用？

Windows 客户端可用是这个插件加 X-Real-IP 的“副作用”，其他客户端应该也会有影响，不过有效期比较短，失效了就再去用用网页版，具体可见 https://github.com/nondanee/UnblockNeteaseMusic/issues/29

身份识别是一样的
不太懂你说的通道的意思 😂

~~嗯我试过了下现在那首可以放了，可能是修复了吧~~ 好像手机上可以，电脑上登录了就不行 =.=

**Comment by shugo-chara** [comment]
> 不好意思感冒了有点难受，没有尽快回复你
> 
> 网易云官方的 Linux 客户端是 deb 的；那些第三方的一般不带 unblock 效果，需要改一下源码，重定向歌曲链接一下就行；vscode 那个扩展有 unblock 功能，但是 vscode 本身是 rpm 可能你也没法用？
> 
> Windows 客户端可用是这个插件加 X-Real-IP 的“副作用”，其他客户端应该也会有影响，不过有效期比较短，失效了就再去用用网页版，具体可见 [nondanee/UnblockNeteaseMusic#29](https://github.com/nondanee/UnblockNeteaseMusic/issues/29)
> 
> 身份识别是一样的
> 不太懂你说的通道的意思 😂
> 
> 嗯我试过了下现在那首可以放了，可能是修复了吧

お大事に。
现在养成了每天出门前在网页端登陆一下解锁移动端的习惯。等煎饼大大的源分享之后就可以安心升级新版云音乐端了，新版智播还是很好用的。

**Comment by nondanee** [comment]
@shugo-chara 
已经和煎饼大大交流过了，对 QQ 音源做了优化 (还没 bump version)，能听的应该更多了，不过还是要求代理回国内 (煎饼大大是无偿提供公共服务器的，有国内代理，我这边暂时不会提供，望理解)

**Comment by zidongtuili** [comment]
保重身体啊。不用急着回我的，反正现在可以听暂时。我是用了这个插件那首歌可以听（也登陆了）。VS code 有个绿色版现在打开了。不知道那个未发布的插件用什么途径安装啊
也就是说windows端可用需要先用这个插件，或者要保持这个插件开启来维持？如果客户端也是通过这个插件才有效的，那我说的那些就没什么价值了……

**Comment by nondanee** [comment]
@zidongtuili 
那个扩展没打过包，不过用 vscode 打开目录开启 debug (F5) 就可以跑起来了，还有些没做，会尽快发布的

使用插件来维持是一个方式，其实是加上 `X-Real-IP` 的作用，用另外方法应该也是可以（没试过不确定）
你说的网页定向可能就是 [nondanee/UnblockNeteaseMusic](https://github.com/nondanee/UnblockNeteaseMusic) 在做的事 😂

**Comment by zidongtuili** [comment]
@nondanee 感谢回复！ f5出来没弹啥界面，不知道是不是要先装ffmpeg啊。还是说在浏览器里输localhost之类的>_<
网页定向估计是现在这个插件，只是我不知道windows上的客户端可以用了是不是因为网页版的插件起的效果（按理说chrome插件应该不能影响外界的程序？只是影响网页里的定向吧。不然太可怕了）

**Comment by shugo-chara** [comment]
> @shugo-chara
> 已经和煎饼大大交流过了，对 QQ 音源做了优化 (还没 bump version)，能听的应该更多了，不过还是要求代理回国内 (煎饼大大是无偿提供公共服务器的，有国内代理，我这边暂时不会提供，望理解)

感谢两位大大~~。公共服务器能理解。只要是有些错误和不能听的歌能听了就好，再不济就继续用网页大法或者每次在手机里跑遍解锁后再听，最起码能更新网易云新版本了。

**Comment by nondanee** [comment]
@zidongtuili 
已经上架了，[可以在商店里找到](https://marketplace.visualstudio.com/items?itemName=nondanee.vsc-netease-music)，点击安装就行，替换 ffmpeg 的方法在 README 里有写。
嗯不是插件直接影响外界程序，只是插件影响了网易云的服务器（里面可能有复杂的逻辑），然后间接影响其它客户端的行为。

**Comment by nondanee** [comment]
@shugo-chara 
QQ 音源可能只是获取 token 的问题，我会酌情提供一个国内的跳板，等下次更新吧！

**Comment by zidongtuili** [comment]
@nondanee 之前也装了，昨天也试了上架的版本，发现f5 debug或者装了上架的版本enable都没有反应，是不是ffmpeg是必须的，然后直接在编辑页面替换了背景（就像介绍里提到的播放器？）。如果ffmpeg是运行必要条件，我可能是替换错误，如果不是必要条件，看来还是我打开方式不对……

**Comment by nondanee** [comment]
@zidongtuili 
在 README 里加了个 demo 和 usage
替换是必要条件，不然会没有声音

**Comment by nondanee** [comment]
@zidongtuili 
我回校了，试了下好像不会从中间开始播放了
代理回国也没有看到之前隐藏直链，降低试听音质的逻辑
麻烦你帮助测试下谢谢

**Comment by nondanee** [comment]
@zidongtuili 
插件 dev 分支有个注入脚本的实现可以试试看有没有原来的问题了（有提升320K）

**Comment by zidongtuili** [comment]
@nondanee 感谢大大，
1. vscode那个其实可以了，就是我一直是微博登陆的，好像还不支持……原来的问题指的是啥（还是说不是vscode相关的）？
2. 好像不从中间开始播放了。没有看到降低试听音质的逻辑是说不用插件也可以320k（如果有320k)？
3. 是让我测试320k还是？其实我也就能看到旁边写的320k，木耳不是每个都能听出来比特率的>_<，除非开了均衡器。还是让我测从中间开始放？
还有我感觉windows上的客户端能用可能不是chrome 插件的原因，因为开机以后不打开网易云音乐网页，客户端也是可以用的。昨天有人用iphone好像还直接可以开网页，我试了我的安卓打开还是封锁了（这个我再确认一下）。
抱歉，好像之前github都没提示我还是我竟然这么久没有开github 了 ....

**Comment by nondanee** [comment]
@nondanee 
1. emmm 我说是这个 chrome 插件，的 dev 分支，有没有从中间开始播或者听一会儿就不卡住了的情况
> dev 分支是直接修改 API 请求返回的音频地址，不做重定向了

2. 320K 看一下 network 里面音源是不是 10MB 左右就知道了
3. emmm 意思用这个 dev 分支的话就不用油猴脚本了（或许可能会冲突？）

emmm 微博登录可能做不了，要微博 OAuth 的，~~绑个海外手机吧，我增加区号支持比较方便~~，好吧我自己试过并不让绑海外手机

装了插件每访问网页版1次的解锁效果大概可以维持1/2天左右，不需要一直开着网页版的

没关系

**Comment by zidongtuili** [comment]
@nondanee 我好象明白了，我这里是欧盟的GDPR锁了，这个插件顺便解锁了，所以我以为是同一个了……

**Comment by nondanee** [comment]
@zidongtuili 
哦是说 GDPR 呀，确实是"顺便"解锁网页版 😂
能解锁1/2天的普通海外墙只是变灰而已，GDPR 打都打不开 ==

UnblockNeteaseMusic 应该会有点帮助
https://github.com/nondanee/UnblockNeteaseMusic/issues/26

**Comment by zidongtuili** [comment]
@nondanee 其实我没注意……还以为是不让听呢。不过很奇怪的就是windows客户端是可以的。
dev版的放了5秒会卡住，不知道是不是别的原因

**Comment by nondanee** [comment]
@zidongtuili 
多谢测试， 5 秒卡住应该会在 console 里抛个异常
好像刷新后或者多点几首就能正常听了？
因为不太稳定我就不更新～

**Comment by zidongtuili** [comment]
@nondanee 
今天测试了一下：好像直接就放不了了……好吧我不知道是不是有别的问题，现在可能不在状态，不要太在意我的测试，console里是
```
Uncaught RangeError: Maximum call stack size exceeded
    at JSON.parse (<anonymous>)
    at asrsea_ (inject.js:6)
    at fake_asrsea (userscript.html?id=97c6b17c-d30d-4697-9463-a7881039593b:300)
    at asrsea_ (inject.js:11)
    at fake_asrsea (userscript.html?id=97c6b17c-d30d-4697-9463-a7881039593b:300)
    at asrsea_ (inject.js:11)
    at fake_asrsea (userscript.html?id=97c6b17c-d30d-4697-9463-a7881039593b:300)
    at asrsea_ (inject.js:11)
    at fake_asrsea (userscript.html?id=97c6b17c-d30d-4697-9463-a7881039593b:300)
    at asrsea_ (inject.js:11)
```

**Comment by zidongtuili** [comment]
测的可能不准，今天直接放不了了。
有这个错
```
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
2userscript.html?id=97c6b17c-d30d-4697-9463-a7881039593b:89 XHR finished loading: POST "https://music.163.com/weapi/feedback/weblog?csrf_token=79c9c42768ca2e2f8a925cd5b3e97aca".
```
也有
```
Uncaught RangeError: Maximum call stack size exceeded
上下文
https://music.163.com/#/discover/recommend/taste
堆叠追踪
inject.js:6 (asrsea_)
chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=97c6b17c-d30d-4697-9463-a7881039593b:300 (fake_asrsea)
```

**Comment by nondanee** [comment]
@zidongtuili emmm 这个爆栈应该是因为插件和 Tampermonkey 的脚本冲突递归了 ==

**Comment by nondanee** [comment]
又开始从上首歌播放到的时间开始了......不知道为什么

**Comment by zidongtuili** [comment]
@nondanee 刚还想说这个……还好你又开了。顺便问问那个js的服务能不能在Android上用termux之类的后台起一个服务然后开网易云的客户端？主要手机电脑用的校园网不是同一个路由。或者vsc的能不能微博登陆了现在？（好像绑定163帐号遇到点麻烦）就是问问的

**Comment by nondanee** [comment]
@zidongtuili 
我跟了一下这个问题好像是因为触发了 playfail（其实没有 failed），它以为还在放原来一首，所以 seek 到了原来的位置，但是我不会改...

可以用 termux，我试过
vsc 现在可以复制 cookie 登录

**Comment by zidongtuili** [comment]
@nondanee 搞定了vsc，不过我突然忽视了一个问题：这个是不是也有现在的问题（其实我不知道是不是完全用的网页版api）。一直用emacs，不知道有没有办法用emacs来控制。现在开一个空的vsc怪怪的

**Comment by nondanee** [comment]
@zidongtuili  
不从头播放的问题？vsc 没有
这个跟用的 api 没关系
而且 vsc 里用的是 linux forward api

emacs 控制应该没办法

**Comment by zidongtuili** [comment]
@nondanee 其实我问的问题已经不是issue了，不过不知道放在哪里问。其实就是 1. 基于vsc的目的是使用vsc的某种功能还是因为大佬平时用的比较方便 2. vsc的版本不会从中间放不是因为api，那么这个是不是可以用到网页版的上面（对比修复playfail），还有就是如果都是直链的话是不是问题会是相同的。3. 这个linux forward api是通过逆向linux客户端（或者说是开源的）得到的吗
好吧纯粹好奇，我会想着找个别的地方发这些的

**Comment by nondanee** [comment]
1. vsc 这个只是我上学期的group project，我其实也并不怎么用
2. 不可以，因为网易云的前端代码做了压缩，我都找不到入口在哪，也不知道为啥会触发，只是在感觉可能的地方（根据 web audio api 的命名）打了断点，跟一下 function call
3. 应该是逆向的吧，我只是站在巨人的肩膀上。API 相关的问题参考这个 https://github.com/Binaryify/NeteaseCloudMusicApi/issues/229#issuecomment-399735231

**Comment by nondanee** [comment]
@zidongtuili 
不从头播放的问题好像现在又好了
不知道为啥==

**Comment by zidongtuili** [comment]
@nondanee 大哥我才用习惯vsc版的……其实还伴随着有些歌卡住
***************************************************
好像那个320k音质的猴油脚本失效了

**Comment by nondanee** [comment]
@zidongtuili 
卡住应该只是 fetch file 的网络问题，你可以打开 f1 打开 "webview 调试工具" 看一下 network
我之前推荐过 rocka 那个客户端，应该挺好用的啊==
https://github.com/Rocket1184/electron-netease-cloud-music

那个油猴脚本我没用，不过网页版用的取 url 接口是换过了，现在有 m4a 格式了，好像网页版是优先 m4a 的？也可能我被灰度测试了？
原来用的是 `/weapi/song/enhance/player/url`
现在用的是 `/weapi/song/enhance/player/url/v1`

**Comment by zidongtuili** [comment]
@nondanee 哦主要系统没有权限，一般编译少了某个库我就傻了。这个看了一下网页不能登陆，不知道是不是改了一个地方就全都能改了（包括登陆）。研究一下改哪里

**Comment by nondanee** [comment]
@zidongtuili 
我试了下，发现挺难的，不太好改，当然也有可能是我姿势不对。

1.给 loginWindow 加了 onBeforeSendHeaders 监听
```
loginWindow.webContents.session.webRequest.onBeforeSendHeaders
```
发现它只对 BrowserWindow 的请求有效果，也就是 login.html 本身有效，对里面 webview 的 webcontents 没作用

2.又给 login.html 里 webview 加了 onBeforeSendHeaders 监听
```
wc.session.webRequest.onBeforeSendHeaders
```
因为在 render 线程，所以只能修改 headers 里已经存在的值，不能加新的 (X-Real-IP)

3.直接在 defaultSession 上改也没有效果
```
session.defaultSession.webRequest.onBeforeSendHeaders
```

到底怎么给 webview setHeaders 我都没找到正面的例子==

https://github.com/electron/electron/issues/4283
https://github.com/electron/electron/issues/16233
https://discuss.atom.io/t/how-to-send-do-not-track-header-in-electron-webview/41485

遂放弃

不然你直接问 @rocka 大佬吧

**Comment by rocka** [comment]
@nondanee 可以用 debugger API，就像上面获取 cookie 的时候一样 ...

```js
wc.debugger.sendCommand('Network.setExtraHTTPHeaders',
  { 
    headers: { 'X-Real-IP': '1.2.4.8' }
  }, 
  (err, res) => {
    if (err) console.warn('setExtraHTTPHeaders failed:', err);
  }
)
```

把这些加在 login.html 中

```js
wc.debugger.sendCommand('Network.enable');
```

的下一行，就可以了：

![image](https://user-images.githubusercontent.com/13914967/57194696-4245a880-6f7c-11e9-88aa-ed6d3be92934.png)

这应该就是想要达到的效果了？

顺便 debugger 的全部 API 可以在 [这里](https://chromedevtools.github.io/devtools-protocol/) 查看

**Comment by nondanee** [comment]
@rocka 多谢大佬，可以用👍，不过这样是图片请求好像也加个这个 header 😂

另外我才发现那个 webview 上有个 partition 😂
试了下在 main thread 里加 headers 是可以的，用这个的方法
https://discuss.atom.io/t/how-to-send-do-not-track-header-in-electron-webview/41485/3

@zidongtuili 
在 `ipcMain.on('showLoginWindow', () => {})` 里面加上
```JavaScript
session.fromPartition('login').webRequest.onBeforeSendHeaders({urls: ['*://music.163.com/*']}, (details, callback) => {
    details.requestHeaders['X-Real-IP'] = '118.88.88.88'
    callback({cancel: false, requestHeaders: details.requestHeaders})
})
```
然后最顶上需要多 import 一个 session
```JavaScript
import { app, BrowserWindow, session, ipcMain, Menu } from 'electron';
```
就好了

**Comment by zidongtuili** [comment]
@nondanee 惊动了两位大佬，太不好意思了。看了一下如果要改的话就要自己编译也就是说要用yarn？然后发现机器上没有，没有root权限，看来……

**Comment by nondanee** [comment]
@zidongtuili 
npm 也可以的
```
npm run dist
npm run build linux
```
或者你跟 @rocka 大佬学一下用 CI build 吧 😂

**Comment by nondanee** [comment]
@zidongtuili 
issue 的问题应该已经解决了
原因我写在 README 里
两边商店的版本更新都已发布
这个 issue 我关了哈~
还有什么需要的话继续 comment 就好了

**Comment by zidongtuili** [comment]
11天没听，天天大波罗![](https://github.githubassets.com/images/icons/emoji/unicode/1f602.png)，不过当时发现320k的脚本不行，当然好久以前就不行了。所以就是弱弱问一下还有救吗

**Comment by nondanee** [comment]
@zidongtuili 
https://greasyfork.org/zh-CN/scripts/386399-neteasemusic-resolution-upgrader
不过现在优先 acc 编码了，`level: exhigh` (极高音质) 应该等同原来的 320k mp3
