### ISSUE TITLE
怎么用

### ISSUE THREAD

**Issue by RicardoWang1** [nondanee/NetEaseMusicWorldPlus#2]
虽然我是工科生，但是我还是没明白怎么用。是直接开电脑上的网易还是网页版的

**Comment by nondanee** [comment]
@RicardoWang1 网页版

**Comment by nondanee** [comment]
@RicardoWang1 
直接作用的是网页版，不过好像对桌面版也有效果，不知道网易云有什么奇怪的机制
使用有问题可以看看这个 https://github.com/nondanee/UnblockNeteaseMusic/issues/29#issuecomment-442347679
