### ISSUE TITLE
能否兼容Listen1 里的网易云功能

### ISSUE THREAD

**Issue by Seekerzero** [nondanee/NetEaseMusicWorldPlus#3]
感谢大佬提供的火狐插件，现在已经可以在网易云官网用了，但是在listen1插件的网易云板块还是会显示有版权问题。

**Comment by nondanee** [comment]
应该是不行的，这是安全问题。
一个插件使用 webRequest API 好像无法作用在另一个插件的请求上
扩展开发文档里没提到，我翻到了一个 issue 你可以看看
[510802 - Security: webRequest API allows intercepting XHR from apps and extensions - chromium - Monorail](https://bugs.chromium.org/p/chromium/issues/detail?id=510802)

**Comment by nondanee** [comment]
Listen 1 是开源的呀，你 fork 一下改它的代码也行嘛，就两个位置
- `js/background.js#L92`
```diff
+ if (details.url.indexOf("://music.163.com/") != -1) {
+     headers.push({
+         name: "X-Real-IP",
+         value: "118.88.88.88"
+     });
+ }
```
- `js/provider/netease.js#L254`
```diff
- sound.url = url
+ sound.url = url.replace(/(m\d+?)(?!c)\.music\.126\.net/, '$1c.music.126.net');
```

**Comment by Seekerzero** [comment]
谢谢大佬告知！另外保重身体！

**Comment by nondanee** [comment]
👌
