### ISSUE TITLE
部分歌單無法播放

### ISSUE THREAD

**Issue by speedcell4** [nondanee/NetEaseMusicWorldPlus#4]
您好, 感謝開發這個插件

坐標日本, 有大部分歌單都無法播放, 直接右下角顯示"播放失敗"的那種.
比如 https://music.163.com/#/playlist?id=2441778630

請問要怎麼處理呢

**Comment by speedcell4** [comment]
啊, 我發現把 chrome 上的插件圖標點成藍色就可以了 😄 
感謝~

**Comment by nondanee** [comment]
👌
