### ISSUE TITLE
网页端500报错

### ISSUE THREAD

**Issue by shugo-chara** [nondanee/NetEaseMusicWorldPlus#5]
chrome插件副作用解锁全平台貌似已经失效了- -
网页端提示500错误。。。不知道还有救么，这个副作用很好用啊。。

**Comment by nondanee** [comment]
500 错误是什么？网页打不开吗？

能不能解锁全平台这个我肯定决定不了啊😂
我这边目前还是全平台解锁状态，不过我不能确定是插件的效果，因为在其他地方我也用了 X-Real-IP 😅，可能会有影响

**Comment by shugo-chara** [comment]
现在好了- -貌似是海外墙的原因，那两天只要打开插件，打开网易云音乐网页就500错误。现在又能正常打开了。。
一直在用那个副作用，客户端打开歌曲列表是灰色时，开着插件登录一下网页版，然后客户端刷新一下就都可以听了，开心。
ps，大佬的android app流产了么。虽然增强器可以用但毕竟需要xp框架。而副作用跟UNM的话有些（首）歌还是灰色听不了，增强器可以，不知道是什么原因。id=512376359

**Comment by nondanee** [comment]
好的，那这个 issue 关掉了啊，我这边好像一直没什么问题
我知道这个效果，身边同学在用
==哦只是没什么精力写
匹配策略可能不一样吧，我刚试了下可以，不过匹配结果和个人网络环境有关
万一因为网络不好超时了没匹配到，失败结果也会被缓存
![image](https://user-images.githubusercontent.com/26399680/54762980-1e2e4200-4c30-11e9-9a4b-e8c5b0d1c04d.png)
