### ISSUE TITLE
一直显示播放失败

### ISSUE THREAD

**Issue by sefeng211** [nondanee/NetEaseMusicWorldPlus#6]
现在在Chrome和Firefox都无法播放歌曲了

我本地改了一下这个固定的ip地址就可以了, 我感觉网易专门的针对了一下这个ip, 改成随机的生成可能会好一点? 
https://github.com/nondanee/NetEaseMusicWorldPlus/blob/master/background.js#L7

**Comment by nondanee** [comment]
不是针对了这个 IP
高频访问的 X-Real-IP 都会被 ban 的

因为我参与的项目习惯用这个 IP
https://github.com/Binaryify/NeteaseCloudMusicApi
https://github.com/nondanee/vsc-netease-music
https://github.com/nondanee/UnblockNeteaseMusic

可能那个 API 服务被人用来爬数据了，然后这个 IP 被 ban 了
不过不是永久 ban，过一段时间会恢复

参考这个 issue
https://github.com/Binaryify/NeteaseCloudMusicApi/issues/442

改成随机的建议
我在这个项目里用了
https://github.com/nondanee/Glee/blob/b3f97234e655b1c8f92d1b3a7a8500287e158198/js/data.js#L281
但是这个项目暂时不用登录
万一被为判频繁切换地点（类似异地登录）我没法对用户的账号负责

**Comment by nondanee** [comment]
@sefeng211 有回应吗？
